project_id = "tjeukbooftbxulkgqljg"

[handle-sms]
verify_jwt = false

[send-verification-code]
verify_jwt = false

[create-checkout]
verify_jwt = false

[generate-fruit-image]
verify_jwt = false

[send-welcome-sms]
verify_jwt = false