import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

const Privacy = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-grow bg-gradient-to-b from-cream to-sage-100">
        <div className="container px-4 py-16 mx-auto">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-4xl font-bold text-sage-800 mb-8">Privacy Notice</h1>
            
            <div className="prose prose-sage max-w-none">
              <p className="text-sage-700 mb-6">
                Last updated: {new Date().toLocaleDateString()}
              </p>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-sage-800 mb-4">1. Introduction</h2>
                <p className="text-sage-700 mb-4">
                  Mother Athena ("we," "our," or "us") respects your privacy and is committed to protecting your personal information. This Privacy Notice explains how we collect, use, disclose, and safeguard your information when you use our services.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-sage-800 mb-4">2. Information We Collect</h2>
                <p className="text-sage-700 mb-4">
                  We collect information that you provide directly to us, including:
                </p>
                <ul className="list-disc pl-6 text-sage-700 mb-4">
                  <li>Name and contact information</li>
                  <li>Due date and pregnancy-related information</li>
                  <li>Communications between you and Mother Athena</li>
                  <li>Usage data and interaction with our services</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-sage-800 mb-4">3. Limitation of Liability</h2>
                <p className="text-sage-700 mb-4">
                  Our services are provided "as is" without any warranties. We are not liable for any damages arising from your use of our services or any information generated by our AI systems. You acknowledge that AI-generated content may be inaccurate or inappropriate for your needs.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-sage-800 mb-4">4. Use of Information</h2>
                <p className="text-sage-700 mb-4">
                  We use your information to:
                </p>
                <ul className="list-disc pl-6 text-sage-700 mb-4">
                  <li>Provide and improve our services</li>
                  <li>Send pregnancy updates and relevant information</li>
                  <li>Respond to your questions and requests</li>
                  <li>Analyze and improve our services</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-sage-800 mb-4">5. Information Sharing</h2>
                <p className="text-sage-700 mb-4">
                  We do not sell your personal information. We may share your information with service providers who assist in operating our services and as required by law.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-sage-800 mb-4">6. Changes to Privacy Notice</h2>
                <p className="text-sage-700 mb-4">
                  We may update this Privacy Notice at any time. Your continued use of our services after any changes indicates your acceptance of the updated Privacy Notice.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-sage-800 mb-4">7. Contact Us</h2>
                <p className="text-sage-700">
                  If you have questions about this Privacy Notice, please contact us at support@motherathena.com
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}

export default Privacy